name: Generate Contributors

on:
  push:
    branches: [main]

jobs:
  contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate contributors list
        uses: dawidd6/action-contributors@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          file: CONTRIBUTORS.md   # output file
          avatar_size: 50
